config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  resources :webhooks, only: [:create]
  root 'products#index'
  post 'checkout/create', to: 'checkout#create'
  get 'success', to: 'checkout#success'
  get 'cancel', to: 'checkout#cancel'

  post "products/add_to_cart/:id" => "products#add_to_cart", as: 'add_to_cart'
  delete "products/remove_from_cart/:id" => "products#remove_from_cart", as: 'remove_from_cart'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord

    monetize :price, as: :price_cents

    def to_s
        name
    end

    def to_builder
        Jbuilder.new do |product|
            product.price stripe_price_id
            product.quantity 1
        end
    end

    after_create do
        product = Stripe::Product.create(
            name: name
        )
        price = Stripe::Price.create(
            product: product.id, 
            unit_amount: self.price, 
            currency: self.currency
        )
        update(stripe_product_id: product.id, stripe_price_id: price.id)
    end


    after_update :create_and_assign_a_new_price, if: :saved_change_to_price?
    
    def create_and_assign_a_new_price
        price = Stripe::Price.create(
            product: self.stripe_product_id, 
            unit_amount: self.price, 
            currency: self.currency
        )
        update(stripe_price_id: price.id)
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def to_s
    email
  end

  after_create do
    customer = Stripe::Customer.create(email: email)
    update(stripe_customer_id: customer.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :initialise_session
    before_action :load_cart

    private

    def initialise_session
        session[:cart] ||= []
    end

    def load_cart
        @cart = Product.find(session[:cart])
    end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
    def create
        # product = Product.find(params[:id])
        @session = Stripe::Checkout::Session.create({
            customer: current_user.stripe_customer_id,
            payment_method_types: ['card'],
            line_items: @cart.collect{|i| i.to_builder.attributes! },
            allow_promotion_codes: true,
            # line_items: [{
            #     # name: product.name,
            #     # amount: product.price * 100,
            #     # currency: 'inr',
            #     price: product.stripe_price_id,
            #     quantity: 1,
            # }],
            mode: 'payment',
            success_url: success_url + "?session_id={CHECKOUT_SESSION_ID}",
            cancel_url: cancel_url
        })
        respond_to do |format|
            format.js
        end
    end

    def success
        if params[:session_id].present?
            session[:cart] = []

            @session = Stripe::Checkout::Session.retrieve({
                id: params[:session_id],
                expand: ["line_items"]
            })
            @line_items = @session.line_items
        else
            redirect_to cancel_url, alert: 'No information about your payment was provided.'
        end
    end

    def cancel
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def add_to_cart
    id = params[:id].to_i
    session[:cart] << id unless session[:cart].include?(id)
    redirect_to products_path
  end

  def remove_from_cart
    id = params[:id].to_i
    session[:cart].delete(id)
    redirect_to products_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :price, :description, :currency, :price_cents)
    end
end

app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
    skip_before_action :authenticate_user!
    skip_before_action :verify_authenticity_token

    def create
        payload = request.body.read
        sig_header = request.env['HTTP_STRIPE_SIGNATURE']
        event = nil

        begin
            event = Stripe::Webhook.construct_event(
                payload, sig_header, Rails.application.credentials[:stripe][:webhook]                
            )
        rescue JSON::ParserError => e
            status 400
            return
        rescue Stripe::SignatureVerificationError => e
            puts 'Signature error'
            puts e
            return
        end

        # handle the event
        case event.type
        when 'checkout.session.completed'
            session = event.data.object
            session = Stripe::Checkout::Session.retrieve({
                id: session.id,
                expand: ["line_items"]
            })
            @line_items = session.line_items
            @line_items.each do |line_item|
                product = Product.find_by(stripe_product_id: line_item.price.product)
                product.increment!(:sales_count)
            end
        end

        render json: { message: 'success' }
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/checkout/cancel.html.erb
<h1>payment cancelled</h1>

app/views/checkout/create.js.erb
var stripe = Stripe("<%= Rails.application.credentials[:stripe][:public] %>");

stripe.redirectToCheckout({
    sessionId: '<%= @session.id %>'
}).then((result) => {
    console.log(result);
});

app/views/checkout/success.html.erb
<h1>payment successful</h1>

<hr/>

Status: <%= @session.payment_status %><br/>
Amount Paid: <%= @session.amount_total %><br/>
Currency: <%= @session.currency %><br/>

<hr/>

<% @line_items.each do |line_item| %>
    Stripe Price: <%= line_item.price %><hr/>
    Stripe Product: <%= line_item.price.product %><hr/>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shoplify</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src='https://js.stripe.com/v3/' ></script>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <%= link_to "Products", products_path %>
    <% if current_user %>
      <%= link_to current_user.email, edit_user_registration_path %>
      <%= link_to 'log out', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'log in', new_user_session_path %>
      <%= link_to 'register', new_user_registration_path %>
    <% end %>
    
    <hr/>
    
    <h3>Shopping Cart</h3>
    <% if @cart.empty? %>
      <p>Your cart is empty</p>
    <% else %>
      <ul>
      <% @cart.each do |product| %>
        <li><%= product.name %></li>
      <% end %>
      </ul>
      <td><%= button_to 'Checkout', checkout_create_path, remote: true, data: { disable_with: 'please wait!!!' }  %></td>
    <% end %>
    <hr/>

    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :currency %>
    <%= form.text_field :currency %>
  </div>

  <div class="field">
    <%= form.label :price_cents %>
    <%= form.number_field :price_cents %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Stripe Id</th>
      <th>Price Id</th>
      <th>Name</th>
      <th>Currency</th>
      <th>Price</th>
      <th>Sales count</th>
      <th>Shopping Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.stripe_product_id %></td>
        <td><%= product.stripe_price_id %></td>
        <td><%= product.name %></td>
        <td><%= product.currency %></td>
        <td><%= product.price_cents %></td>
        <td><%= product.sales_count %></td>
        <td>
          <% if @cart.include?(product) %>
            <%= button_to 'Remove from cart', remove_from_cart_path(product), method: :delete %>
          <% else %>
            <%= button_to 'Add to cart', add_to_cart_path(product), method: :post %>
          <% end %>
        </td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price_cents %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>